name = "ChairmarksExtras"
uuid = "1f012879-3887-41d0-bd88-38cb7d73fb12"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Chairmarks = "1.3.1"
Reexport = "1.2.2"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
